# Generated by Django 4.2.11 on 2026-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('git', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('imagem', models.URLField()),
            ],
        ),
    ]
