# Generated by Django 4.2.11 on 2026-04-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoal',
            old_name='linkedin',
            new_name='linked',
        ),
    ]
